# Generated by Django 5.1 on 2024-08-18 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tipoinmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='tipo_inmueble',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tipoinmueble'),
            preserve_default=False,
        ),
    ]
